### ISSUE TITLE
Specify title for directory

### ISSUE THREAD

**Issue by elliotchance** [uvtc/rippledoc#4]
At the moment the only way to specify the title of a directory is by naming it as such - this is pretty limited as you may want to put all sort of punctuation in the title.

Perhaps use the `toc.conf` file with pandoc syntax?

```
% My Super Cool Directory!
a.md
less-cool-dir
b.md
```

**Comment by uvtc** [comment]
Thank you, but I prefer the doc navigation to directly mirror the directory names.
